// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDirectMembers = `-- name: CountDirectMembers :one
SELECT COUNT(*) FROM people
WHERE group_id = $1
`

func (q *Queries) CountDirectMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalMembers = `-- name: CountTotalMembers :one
WITH RECURSIVE group_tree AS (
    SELECT g.id FROM groups g WHERE g.id = $1
    UNION ALL
    SELECT g.id FROM groups g
    INNER JOIN group_tree gt ON g.parent_id = gt.id
)
SELECT COUNT(*) FROM people p
WHERE p.group_id IN (SELECT gt.id FROM group_tree gt)
`

func (q *Queries) CountTotalMembers(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalMembers, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (id, name, parent_id)
VALUES ($1, $2, $3)
RETURNING id, parent_id, name
`

type InsertGroupParams struct {
	Id       int64
	Name     string
	ParentId pgtype.Int8
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup, arg.Id, arg.Name, arg.ParentId)
	var i Group
	err := row.Scan(&i.Id, &i.ParentId, &i.Name)
	return i, err
}

const selectAllGroups = `-- name: SelectAllGroups :many
SELECT id, parent_id, name FROM groups
`

func (q *Queries) SelectAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, selectAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Id, &i.ParentId, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChildGroups = `-- name: SelectChildGroups :many
SELECT id, parent_id, name FROM groups
WHERE parent_id = $1
`

func (q *Queries) SelectChildGroups(ctx context.Context, parentID pgtype.Int8) ([]Group, error) {
	rows, err := q.db.Query(ctx, selectChildGroups, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Id, &i.ParentId, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGroupById = `-- name: SelectGroupById :one
SELECT id, parent_id, name FROM groups
WHERE id = $1
`

func (q *Queries) SelectGroupById(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, selectGroupById, id)
	var i Group
	err := row.Scan(&i.Id, &i.ParentId, &i.Name)
	return i, err
}

const selectGroupsByName = `-- name: SelectGroupsByName :many
SELECT id, parent_id, name FROM groups
WHERE name = $1
`

func (q *Queries) SelectGroupsByName(ctx context.Context, name string) ([]Group, error) {
	rows, err := q.db.Query(ctx, selectGroupsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Id, &i.ParentId, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups
SET name = $1, parent_id = $2
WHERE id = $3
`

type UpdateGroupParams struct {
	Name     string
	ParentId pgtype.Int8
	Id       int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.Name, arg.ParentId, arg.Id)
	return err
}
