// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	Id       int64
	ParentId pgtype.Int8
	Name     string
}

type Person struct {
	Id        int64
	Firstname string
	Lastname  string
	Birthday  pgtype.Date
	GroupId   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
