// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deepSelectPersonByGroupId = `-- name: DeepSelectPersonByGroupId :many
WITH RECURSIVE subgroups AS (
    SELECT groups.id FROM groups
    WHERE groups.id = $1

    UNION ALL

    SELECT g.id FROM groups g
    INNER JOIN subgroups s ON g.parent_id = s.id
)
SELECT p.id, p.firstname, p.lastname, p.birthday, p.group_id, p.created_at, p.updated_at FROM people p
INNER JOIN subgroups s ON p.group_id = s.id
`

func (q *Queries) DeepSelectPersonByGroupId(ctx context.Context, id int64) ([]Person, error) {
	rows, err := q.db.Query(ctx, deepSelectPersonByGroupId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.Id,
			&i.Firstname,
			&i.Lastname,
			&i.Birthday,
			&i.GroupId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const insertPerson = `-- name: InsertPerson :exec
INSERT INTO people (id, firstname, lastname, birthday, group_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPersonParams struct {
	Id        int64
	Firstname string
	Lastname  string
	Birthday  pgtype.Date
	GroupId   int64
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.Exec(ctx, insertPerson,
		arg.Id,
		arg.Firstname,
		arg.Lastname,
		arg.Birthday,
		arg.GroupId,
	)
	return err
}

const selectPersonByGroupId = `-- name: SelectPersonByGroupId :many
SELECT id, firstname, lastname, birthday, group_id, created_at, updated_at FROM people
WHERE group_id = $1
`

func (q *Queries) SelectPersonByGroupId(ctx context.Context, groupID int64) ([]Person, error) {
	rows, err := q.db.Query(ctx, selectPersonByGroupId, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.Id,
			&i.Firstname,
			&i.Lastname,
			&i.Birthday,
			&i.GroupId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPersonById = `-- name: SelectPersonById :one
SELECT id, firstname, lastname, birthday, group_id, created_at, updated_at FROM people
WHERE id = $1
`

func (q *Queries) SelectPersonById(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRow(ctx, selectPersonById, id)
	var i Person
	err := row.Scan(
		&i.Id,
		&i.Firstname,
		&i.Lastname,
		&i.Birthday,
		&i.GroupId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE people
SET firstname = $2, lastname = $3, birthday = $4, group_id = $5
WHERE id = $1
`

type UpdatePersonParams struct {
	Id        int64
	Firstname string
	Lastname  string
	Birthday  pgtype.Date
	GroupId   int64
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.Exec(ctx, updatePerson,
		arg.Id,
		arg.Firstname,
		arg.Lastname,
		arg.Birthday,
		arg.GroupId,
	)
	return err
}
