-- +goose Up
ALTER TABLE people
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE people
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;
